name: Terraform Checks

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'terraform/**'
  push:
    branches:
      - main
    paths:
    - 'terraform/**'

permissions:
  contents: read

jobs:
  terraform-fmt:
    name: 'Terraform fmt'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v2.4.0

      - uses: hashicorp/setup-terraform@17d4c9b8043b238f6f35641cdd8433da1e6f3867 # v2.0.0
        with:
          # TODO: extract terraform from the tf file when we have pinned
          terraform_version: 1.1.6

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive .

  terraform-validate:
    name: 'Terraform validate'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/gcp/modules/sigstore

    steps:
      - name: 'Checkout'
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v2.4.0

      - uses: hashicorp/setup-terraform@17d4c9b8043b238f6f35641cdd8433da1e6f3867 # v2.0.0
        with:
          # TODO: extract terraform from the tf file when we have pinned
          terraform_version: 1.1.6

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate


  terraform-tfsec:
    name: 'Terraform tfsec'
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: 'Checkout'
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v2.4.0

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@56bc584a8377626a31e511056772298ccfa69501 # v0.1.0
        with:
          sarif_file: tfsec.sarif
          working_directory: '.'
          tfsec_args: --force-all-dirs --verbose

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@1ed1437484560351c5be56cf73a48a279d116b78 # v2.1.8
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
